apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-app
      lang: golang
  template:
    metadata:
      labels:
        app: go-app
        lang: golang
    spec:
      containers:
      - name: my-go-app
        image: go-app